import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import vm from 'node:vm';
import { createHash } from 'node:crypto';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = name => readFile(path.join(root, 'src', name), 'utf8');
const [template, css, bootstrap, core, portable, motion, gestures, scenes, app] = await Promise.all(['shell.html', 'style.css', 'bootstrap.js', 'core.js', 'portable.js', 'motion.js', 'gestures.js', 'scenes.js', 'app.js'].map(read));
const script = `(() => {\n'use strict';\n${core.replace(/^export /gm, '')}\n${portable.replace(/^export /gm, '')}\n${motion.replace(/^export /gm, '')}\n${gestures.replace(/^export /gm, '')}\n${scenes}\n${app}\n})();`;
new vm.Script(script, { filename: 'lucky-draw.js' });
new vm.Script(bootstrap, { filename: 'bootstrap.js' });
if (/<\/script/i.test(script) || /<\/script/i.test(bootstrap) || /<\/style/i.test(css)) throw new Error('Unsafe embedded closing tag');
const output = template.replace('/* INLINE_CSS */', () => css).replace('/* INLINE_BOOTSTRAP */', () => bootstrap).replace('/* INLINE_JS */', () => script);
if (/<(?:script|img|iframe|link)\b[^>]*\b(?:src|href)\s*=\s*["'](?:https?:)?\/\//i.test(output)) throw new Error('External runtime asset found');
await mkdir(path.join(root, 'dist'), { recursive: true });
await writeFile(path.join(root, 'index.html'), output, 'utf8');
await writeFile(path.join(root, 'dist', 'index.html'), output, 'utf8');
const buildId = createHash('sha256').update(output).digest('hex').slice(0, 16);
for (const file of ['app.webmanifest', 'icon.svg']) await writeFile(path.join(root, 'dist', file), await read(file));
await writeFile(path.join(root, 'dist', 'sw.js'), (await read('sw.js')).replace('__BUILD_ID__', buildId));
console.log(`Built index.html (${Buffer.byteLength(output).toLocaleString()} bytes), no external assets.`);
